- core_prng/distributions.pxd
- core_prng/dsfmt.pyx
- core_prng/generator.pyx
- core_prng/mt19937.pyx
- core_prng/pcg32.pyx
- core_prng/pcg64.pyx
- core_prng/philox.pyx
- core_prng/src/distributions/distributions.c
- core_prng/src/distributions/distributions.h
- core_prng/tests/test_against_numpy.py
- core_prng/tests/test_direct.py
- core_prng/tests/test_numpy_mt19937.py
- core_prng/tests/test_smoke.py
- core_prng/threefry.pyx
- core_prng/threefry32.pyx
- core_prng/xoroshiro128.pyx
- core_prng/xorshift1024.pyx
- examples/cython/extending_distributions.pyx
- examples/numba/extending_distributions.py
Drop Box-Muller and supported infrastructure
> REF: Drop Box-Muller

- .gitignore
- README.md
- doc/source/conf.py
- randomgen/__init__.py
- setup.py
> DOC: Change theme

- randomgen/common.pyx
- randomgen/generator.pyx
Replace conversion to long with int64
> CLN: Remove references to long

- .travis.yml
- README.md
- README.rst
- doc/source/change-log.rst
- doc/source/extending.rst
- doc/source/index.rst
- doc/source/legacy.rst
- doc/source/multithreading.rst
- doc/source/new-or-different.rst
- randomgen/common.pxd
- randomgen/common.pyx
- randomgen/legacy/__init__.py
- randomgen/legacy/legacy.pyx
- randomgen/legacy/legacy_distributions.pxd
- randomgen/src/distributions/distributions.c
- randomgen/src/distributions/distributions.h
- randomgen/src/legacy/distributions-boxmuller.c
- randomgen/src/legacy/distributions-boxmuller.h
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_numpy_mt19937.py
- requirements.txt
- setup.py
Add legacy distributions through new generator
> ENH: Add Box-Muller gauss

- randomgen/examples/cython/setup.py
- randomgen/examples/numba/extending.py
- randomgen/examples/numba/extending_distributions.py
- randomgen/generator.pyx
- randomgen/legacy/_legacy.pyx
- randomgen/legacy/legacy.py
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_numpy_mt19937.py
- randomgen/tests/test_numpy_mt19937_regressions.py
- randomgen/tests/test_smoke.py
Sync with upstream changes (all doc)
Clean flake8 issues
> SYNC/CLN: Sync with upstream changes

- setup.py
> BLD: Add lm flag for non-windows platforms

- README.md
Dear Kevin,
Very nice repository here! The PR is for two typos that made URLs invalid.
> typos in URLs

- README.md
- README.rst
- randomgen/generator.pyx
- randomgen/tests/test_numpy_mt19937.py
Allow empty choices to sync with upstream changes
> ENH: Allow empty choice

- README.rst
- doc/source/change-log.rst
- randomgen/examples/numba/extending.py
- randomgen/generator.pyx
- randomgen/legacy/_legacy.pyx
- randomgen/src/distributions/distributions.c
- randomgen/src/legacy/distributions-boxmuller.c
- randomgen/src/mt19937/randomkit.c
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_direct.py
- randomgen/tests/test_numpy_mt19937.py
- randomgen/tests/test_smoke.py
> MAINT: Sync with recent upstream changes

- LICENSE.md
- MANIFEST.in
- randomgen/_testing.py
- randomgen/src/common/LICENSE.md
- randomgen/src/distributions/LICENSE.md
- randomgen/src/dsfmt/LICENSE.md
- randomgen/src/entropy/LICENSE.md
- randomgen/src/legacy/LICENSE.md
- randomgen/src/mt19937/LICENSE.md
- randomgen/src/pcg32/LICENSE.md
- randomgen/src/pcg64/LICENSE.md
- randomgen/src/philox/LICENSE.md
- randomgen/src/splitmix64/LICENSE.md
- randomgen/src/threefry/LICENSE.md
- randomgen/src/threefry32/LICENSE.md
- randomgen/src/xoroshiro128/LICENSE.md
- randomgen/src/xorshift1024/LICENSE.md
- setup.cfg
Add license files for project and components
Fix small issue with regex
> DOC/MAINT: Add license

- randomgen/src/pcg64/pcg64.h
Add umul128 intrinsic support for 64bit windows
> REF: Add path using umul

- randomgen/src/aligned_malloc/aligned_malloc.h
- randomgen/src/distributions/distributions.h
- randomgen/src/entropy/entropy.h
- randomgen/src/legacy/distributions-boxmuller.h
- randomgen/src/philox/philox.h
- randomgen/src/threefry/threefry.h
- randomgen/src/threefry32/threefry32.h
- randomgen/src/xoroshiro128/xoroshiro128.h
- randomgen/src/xorshift1024/xorshift1024.h
> CLN: Add guards to headers

- .travis.yml
- README.md
- README.rst
- randomgen/common.pxd
- randomgen/common.pyx
- randomgen/generator.pyx
- randomgen/tests/test_numpy_mt19937.py
- randomgen/tests/test_numpy_mt19937_regressions.py
Sync upstream changes in numpy/numpy#11613, numpy/numpy#11771, and
numpy/numpy#12089
> UPD: Sync with upstream changes

- benchmark.py
- doc/source/conf.py
- doc/source/performance.py
- randomgen/tests/test_numpy_mt19937.py
Refactor benchmark with more options
Clean code for PEP8 violations
> REF: Refactor benchmark

- .travis.yml
- README.md
- README.rst
- ci/conda-install.sh
- ci/pypi-install.sh
- doc/source/change-log.rst
- requirements.txt
> RLS: Release 1.16.0

- doc/source/change-log.rst
- randomgen/generator.pyx
- randomgen/tests/test_numpy_mt19937.py
Update doc strings and some minor parameter checks to reflect upstream changes.
> DOC: UPdate docs to reflect upstream changes

- randomgen/common.pyx
- randomgen/generator.pyx
- randomgen/tests/test_against_numpy.py
Ensure that parameter checks also guard against nans.
> Nan guards

- randomgen/generator.pyx
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_numpy_mt19937.py
Cast covariance to double to ensure that tol is a meaningful test
> ENH: Cast covariance in mvnormal

- LICENSE.md
- randomgen/src/distributions/LICENSE.md
Dual license under NCSA and 3-clause BSD
Include sublicense for Julia
> DOC: Update license

- randomgen/legacy/_legacy.pyx
- randomgen/legacy/legacy.py
Add set/get states
Hide new attributes
Synchronize rand/random_sample/randint
> ENH: Move Legacy closer to numpy

- randomgen/mtrand.pyx
- randomgen/pickle.py
- randomgen/tests/test_randomstate.py
- randomgen/tests/test_randomstate_regression.py
Fix and test set and get state attributes
Verify pickle works
Complete testing
> BUG: Fix set and get state attributes

- randomgen/generator.pyx
Sync all distirbution docstrings with numpy
> DOC: Carefully sync docstrings with numpy

- .coveragerc
- randomgen/common.pyx
- randomgen/generator.pyx
- randomgen/legacy/legacy.py
- randomgen/mt19937.pyx
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_direct.py
- randomgen/tests/test_edges.py
- randomgen/tests/test_numpy_mt19937.py
- randomgen/tests/test_smoke.py
- randomgen/xoshiro256starstar.pyx
Improve coverage and fix bugs discovered
> Generator coverage

- .travis.yml
- appveyor.yml
- randomgen/mtrand.pyx
- randomgen/tests/test_direct.py
- setup.py
Restore Python 2.7 compatibility
> BUG: Restore Python 2.7

- doc/source/change-log.rst
- randomgen/distributions.pxd
- randomgen/generator.pyx
- randomgen/mtrand.pyx
- randomgen/src/distributions/distributions.c
- randomgen/src/distributions/distributions.h
- randomgen/tests/test_generator_mt19937.py
Add broadcasting to multinomial
xref numpy/numpy#9710
> ENH: Add broadcasting to multinomial

- randomgen/generator.pyx
- randomgen/src/distributions/distributions.c
- randomgen/tests/test_generator_mt19937.py
Enable Hypergeometric to work with 0 samples
xref numpy/numpy#9237
> ENH: Enable 0 samples in hypergeometric

- randomgen/src/distributions/distributions.c
- randomgen/tests/test_generator_mt19937.py
> MAINT: Sync NumPy 9824

- randomgen/generator.pyx
- randomgen/tests/test_generator_mt19937.py
Add input protection in multinomial
> ENH: Add protection for multinomial

- randomgen/dsfmt.pyx
- randomgen/generator.pyx
- randomgen/mt19937.pyx
- randomgen/mtrand.pyx
- randomgen/pcg32.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256starstar.pyx
- randomgen/xoshiro512starstar.pyx
And point docstring to random_sample
> DOC: Add functions for ranf and sample

- randomgen/generator.pyx
- randomgen/tests/test_generator_mt19937.py
> ENH: Add axis to choice

- randomgen/src/distributions/distributions.c
> BUG: Fix typecast in zipf

- randomgen/generator.pyx
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_generator_mt19937.py
Improve choice in all cases, especially when size is small relative to population size
> Choice small alt

- randomgen/pcg64.pyx
- randomgen/src/pcg64/pcg64.c
- randomgen/src/pcg64/pcg64.h
- setup.py
Remove Cython conditional compilation and use preprocessor only
> MAINT: Remove Cython conditionals

- doc/source/change-log.rst
- doc/source/new-or-different.rst
- randomgen/dsfmt.pyx
- randomgen/entropy.pyx
- randomgen/generator.pyx
- randomgen/mt19937.pyx
- randomgen/mtrand.pyx
- randomgen/pcg32.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256starstar.pyx
- randomgen/xoshiro512starstar.pyx
Improve and standardize class docstrings
> DOC: Improve and standardize docs

- randomgen/src/distributions/distributions.c
Avoid log of 0 where it causes issues
> BUG: Carefully check log is well defined

- README.md
- README.rst
- benchmark.py
- doc/source/generator.rst
- doc/source/index.rst
- doc/source/new-or-different.rst
- randomgen/generator.pyx
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_direct.py
- randomgen/tests/test_final_release_changes.py
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_smoke.py
Rename random_sample to random and deprecate random_sample
> REF: Rename random_sample to random

- randomgen/generator.pyx
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_smoke.py
Discourage users from these functions, which are going away
> MAINT: Deprecate rand and randn

- benchmark.py
- doc/source/performance.py
- randomgen/generator.pyx
- randomgen/legacy_distributions.pxd
- randomgen/mtrand.pyx
- randomgen/src/legacy/distributions-boxmuller.c
- randomgen/src/legacy/distributions-boxmuller.h
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_direct.py
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_generator_mt19937_regressions.py
- randomgen/tests/test_smoke.py
> MAINT: Rename brng property to bit_generator

- doc/source/new-or-different.rst
- randomgen/dsfmt.pyx
- randomgen/mt19937.pyx
- randomgen/pcg32.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/tests/test_direct.py
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256starstar.pyx
- randomgen/xoshiro512starstar.pyx
Remove this method for creating a generator
> MAINT: Remove generators from bit_generators

- randomgen/generator.pyx
- randomgen/mtrand.pyx
Switch from heap to stack for Generator and RandomState
> ENH: Switch to stack allocation

- README.md
- doc/source/change-log.rst
- doc/source/index.rst
Update release notes and clarify warning
> DOC: Update release notes for 1.17

- README.rst
- randomgen/dsfmt.pyx
- randomgen/generator.pyx
- randomgen/mt19937.pyx
- randomgen/mtrand.pyx
- randomgen/pcg32.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256starstar.pyx
- randomgen/xoshiro512starstar.pyx
Simplify using stack allocation where possible
> ENH: Use stack allocation

- randomgen/dsfmt.pyx
- randomgen/mt19937.pyx
- randomgen/pcg32.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/tests/test_smoke.py
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256starstar.pyx
- randomgen/xoshiro512starstar.pyx
- setup.py
Jumped implementations were all flawed.  Correct this mistakes.
> BUG: Fix jumped implementations

- randomgen/generator.pyx
- randomgen/tests/test_final_release_changes.py
Ensure deprecations are raised, and fix any missed
> TST: Test more of the deprecations

- randomgen/_pickle.py
- randomgen/bounded_integers.pyx.in
- randomgen/examples/numba/extending.py
- randomgen/examples/numba/extending_distributions.py
- randomgen/mtrand.pyx
- randomgen/tests/test_direct.py
- randomgen/tests/test_final_release_changes.py
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_smoke.py
Fix rename in pickle
Clean pep8 errors
Order imports
> MAINT: Clean code missed

- .drone.yml
- requirements-dev.txt
> TST: Add drone.io for ARM

- .drone.yml
- README.md
- README.rst
- randomgen/legacy_distributions.pxd
- randomgen/mtrand.pyx
- randomgen/src/distributions/distributions.c
- randomgen/src/distributions/distributions.h
- randomgen/src/legacy/distributions-boxmuller.c
- randomgen/src/legacy/distributions-boxmuller.h
- setup.py
Switch to log1p to preserve precision
> MAINT: Use log1p inplace log(1-x)

- .gitignore
- randomgen/legacy/bounded_integers.pxd.in
- randomgen/legacy/bounded_integers.pyx.in
- randomgen/legacy/distributions.pxd
- randomgen/mtrand.pyx
- randomgen/src/distributions/distributions.c
- randomgen/src/distributions/distributions.h
- randomgen/src/legacy/legacy-distributions.c
- randomgen/src/legacy/legacy-distributions.h
- setup.py
Refactor legacy integers out of distributions
Reorganize legacy to a single location
> MAINT: Reorganize and refactor integers

- randomgen/mtrand.pyx
- randomgen/src/distributions/distributions.c
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_randomstate.py
Fix incorrect clause end
Add integer-generator tests
> BUG: Fix multinomial

- .travis.yml
- README.md
- README.rst
- ci/pypi-install.sh
- randomgen/_pickle.py
- randomgen/api.pxd
- randomgen/bounded_integers.pyx.in
- randomgen/common.pyx
- randomgen/generator.pyx
- randomgen/mtrand.pyx
- requirements.txt
- setup.py
Revert earlier increase in Cython while keeping new API
> MAINT: Allow NP17 API everywhere

- randomgen/common.pxd
- randomgen/common.pyx
- randomgen/generator.pyx
- randomgen/mtrand.pyx
- randomgen/src/distributions/distributions.c
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_randomstate.py
Update for int64 typed generator
Fix small backward compat issue
> ENH: Update poisson lam max

- randomgen/dsfmt.pyx
- randomgen/mt19937.pyx
- randomgen/mt64.pyx
- randomgen/pcg32.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256.pyx
- randomgen/xoshiro512.pyx
> DOC: Add doc for lock

- randomgen/bounded_integers.pyx.in
- randomgen/common.pyx
- randomgen/dsfmt.pyx
- randomgen/entropy.pyx
- randomgen/generator.pyx
- randomgen/mt19937.pyx
- randomgen/mt64.pyx
- randomgen/pcg32.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256.pyx
- randomgen/xoshiro512.pyx
Use __all__ to hide unwanted attributes
> MAINT: Add __all__ to help imports

- randomgen/src/pcg64/pcg64.h
Use intrinsic _rotr for performance on Windows
> ENH: Use intrinsic rotr in PCG

- randomgen/generator.pyx
- randomgen/mtrand.pyx
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_randomstate_regression.py
Lets uers know this is not supported
> ENH: Warn on integers/randint endainess settings

- randomgen/src/pcg64/pcg64.h
Use Robert Kern's (@rkern) patch for perforamnce in PCG64
> PERF: Use intrinsic to improve PCG64 performance

- randomgen/pcg64.pyx
- randomgen/tests/test_direct.py
Fix default PCG jump size based on authors recommendation
> MAINT: Fix default PCG jump size

- .cirrus.yml
- README.md
- README.rst
- ci/cirrus-install.sh
> BLD: Use cirrus for FreeBSD[skip appveyor][skip travis][skip drone]

- randomgen/tests/practrand-driver.py
Add a driver that simplifies using generators with PractRand
> TST: Add a generic driver program for PractRand

- randomgen/generator.pyx
- randomgen/mtrand.pyx
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_randomstate.py
Cast to contiguous when required
> BUG: Ensure arrays are contiguous

- randomgen/common.pxd
- randomgen/common.pyx
- randomgen/dsfmt.pyx
- randomgen/mt19937.pyx
- randomgen/mt64.pyx
- randomgen/pcg64.pyx
- randomgen/philox.pyx
- randomgen/sfmt.pyx
- randomgen/tests/test_direct.py
- randomgen/threefry.pyx
- randomgen/threefry32.pyx
- randomgen/xoroshiro128.pyx
- randomgen/xorshift1024.pyx
- randomgen/xoshiro256.pyx
- randomgen/xoshiro512.pyx
Check state arrays have the correct size and bitness
> ENH: Add checks for state arrays

- randomgen/src/aesctr/aesctr.c
- randomgen/src/aesctr/aesctr.h
Use a union to simplify future changes
> MAINT: Use a union for data type

- doc/source/index.rst
- randomgen/src/legacy/legacy-distributions.c
> MAINT: Fix small issues

- randomgen/philox.pxd.in
- randomgen/philox.pyx
- randomgen/src/philox/philox.c
- randomgen/src/philox/philox.h
- randomgen/src/threefry/threefry.c
- randomgen/src/threefry/threefry.h
- randomgen/threefry.pxd.in
- randomgen/threefry.pyx
Refactor to use a union to reduce state size
> MAINT: Refactor Philx and ThreeFry

- randomgen/aes.pyx
- randomgen/chacha.pyx
- randomgen/philox.pxd.in
- randomgen/philox.pyx
- randomgen/src/aesctr/aesctr.c
- randomgen/src/aesctr/aesctr.h
- randomgen/src/chacha/chacha.c
- randomgen/src/chacha/chacha.h
- randomgen/src/philox/philox.c
- randomgen/src/philox/philox.h
- randomgen/src/threefry/threefry.c
- randomgen/src/threefry/threefry.h
- randomgen/tests/test_direct.py
- randomgen/tests/test_smoke.py
- randomgen/threefry.pxd.in
- randomgen/threefry.pyx
> BUG: Fix ThreeFry and Philox advance

- randomgen/jsf.pyx
- randomgen/src/jsf/jsf.c
- randomgen/src/jsf/jsf.h
- randomgen/tests/test_direct.py
Add optional seed size for JSF
> ENH: Increase JSF seed size

- randomgen/aes.pyx
- randomgen/src/aesctr/LICENSE.md
- randomgen/src/aesctr/aesctr.c
- randomgen/src/aesctr/aesctr.h
- randomgen/src/aesctr/softaes.h
- randomgen/src/aesctr/tiny-aes.c
- randomgen/src/aesctr/tiny-aes.h
- randomgen/tests/test_direct.py
Add software only AES counter for uniformity
> ENH: Add software-only AES

- randomgen/dsfmt.pyx
- randomgen/mt19937.pyx
- randomgen/mt64.pyx
- randomgen/sfmt.pyx
Standardize entropy initialization for MT generators
Clarify docstrings
> ENH/DOC: Standardize entropy init for MT

- randomgen/src/pcg64/pcg64.h
Fix initialization bug in PCG64
> BUG: Fix initialization bug in PCG64

- benchmark.py
- doc/source/performance.py
- doc/source/performance.rst
- randomgen/tests/test_direct.py
Regenerate performance measures
> DOC: Improve performance measurement

- randomgen/src/pcg64/pcg64.c
- randomgen/src/pcg64/pcg64.h
Simplify PCG64 using some of the changes in NumPy
> MAINT: Improve PCG64

- .travis.yml
- randomgen/seed_sequence.pyx
- setup.py
Add debugging and a debug build to Travis
> MAINT: Add a debug build

- randomgen/src/common/inttypes.h
- randomgen/src/common/randomgen_immintrin.h
- randomgen/src/common/standalone/Python.h
- randomgen/src/common/standalone/aligned_malloc.h
- randomgen/src/common/standalone/npy_common.h
- randomgen/src/common/standalone/npy_math.h
Small reorder to improve compat and reformatting
> MAINT: Small changes to improve stand alone

- .travis.yml
- ci/install-gcc-8.sh
> MAINT: Use GCC 8

- randomgen/aes.pyx
- randomgen/speck128.pxd
- randomgen/speck128.pyx
- randomgen/src/speck-128/speck-128-common.h
- randomgen/src/speck-128/speck-128-sse.h
- randomgen/src/speck-128/speck-128.h
- randomgen/tests/test_direct.py
- setup.py
Allow SPECK to be used in reduced round variants
> ENH: Add reduced-rounds to SPECK

- randomgen/generator.pyx
- randomgen/tests/test_smoke.py
> ENH: Restore random_unitegers

- .drone.yml
- .travis.yml
- doc/source/conf.py
- randomgen/src/distributions/distributions.c
- requirements-dev.txt
Update to sphinx material
Fix missed 2**32 case for randint
> DOC/BUG: Update to sphinx-material

- .travis.yml
- randomgen/src/common/stdbool.h
Add a value and switch to unsigned char
> MAINT: Fix small issues in stdbool

- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_generator_117.py
Add initial testing to limit drift
> TST: Add initial testing against NumPy 1.17+ Generator

- .travis.yml
- doc/source/change-log.rst
- doc/source/index.rst
- randomgen/generator.pyx
- randomgen/tests/test_against_numpy.py
- randomgen/tests/test_final_release_changes.py
- randomgen/tests/test_generator_117.py
- randomgen/tests/test_generator_mt19937.py
Bring in upstream changes in choice
> ENH: Synchronize upstream improvements in choice

- randomgen/tests/test_generator_mt19937_regressions.py
- randomgen/tests/test_randomstate_regression.py
- tools/practrand-driver.py
> MAINT: Update practrand driver

- randomgen/common.pyx
- randomgen/tests/test_generator_mt19937.py
- randomgen/tests/test_smoke.py
Ensure output size is consistent with broadcast shape
> BUG: Check output size when broadcasting

- randomgen/aes.pyx
- randomgen/common.pxd
- randomgen/common.pyx
- randomgen/hc128.pyx
- randomgen/jsf.pyx
- randomgen/philox.pyx
- randomgen/src/aesctr/aesctr.c
- randomgen/src/aesctr/aesctr.h
- randomgen/tests/_shims.pyx
- randomgen/tests/test_common.py
- randomgen/tests/test_generator_mt19937.py
- randomgen/threefry.pyx
- setup.py
Begin adding support for BE arch
> BUG: Add limited support for BE

- randomgen/aes.pyx
- randomgen/src/aesctr/aesctr.c
- randomgen/src/aesctr/aesctr.h
Correct seeding and generation on BE
> BUG: Fix AESCounter for BE

- .drone.yml
- randomgen/src/dsfmt/dsfmt.c
- setup.py
Fix GCC compilation error in init by array fo rDSFMT
> BUG: Fix incorrect compilation on GCC/ARM

- tools/practrand-driver.py
> MAINT: Small improvements to tester

- tools/practrand-driver-config.py
- tools/practrand-driver.py
> ENH: Add example of a practrand driver config

- doc/source/index.rst
- doc/source/parallel.rst
> DOC: Update parallel docs

- doc/source/custom-bit-generators.ipynb
- doc/source/spelling_wordlist.txt
Switch to JSF for comparability
> DOC: Update notebook

- doc/source/bit_generators/rdrand.rst
- randomgen/rdrand.pyx
- randomgen/src/rdrand/rdrand.h
Explain the basic PRNG
More details about exceptions
closes #249
> DOC: Provide further explanation of the choices in RDRAND

- setup.cfg
- setup.py
Import setuptools first to avoid warning and any related issues
> MAINT: Import setuptools first

- doc/source/change-log.rst
> RLS: v1.19.3 release change log

- appveyor.yml
Update numba to use the channel
> MAINT: Update numba in appveyor

- .drone.yml
> MAINT: Update Drone

- randomgen/src/philox/philox.c
- randomgen/src/threefry/threefry.c
Correct bug to precent out of bounds access
> BUG: Correct buffer access buf in ThreeFry and Philox

- ci/azure/azure_template_posix.yml
- ci/azure/install-posix.sh
- ci/azure/update_path.sh
> MAINT: Add conda-based test run

- azure-pipelines.yml
- ci/azure/azure_template_posix.yml
Add Azure and codecov coverage
> MAINT: Add coverage

- randomgen/aes.pyx
- randomgen/tests/test_direct.py
Wrap around at 2**128 to avoid overflow
closes #267
> BUG: Allow AESCounter to be set to all values

- randomgen/chacha.pyx
- randomgen/speck128.pyx
Remove -1 in period calculation
closes #269
> DOC: Correct periods of SPECK128 and ChaCha20

- randomgen/philox.pyx
- randomgen/threefry.pyx
Corrext period to reflect multiple draws per counter increase
closes #272
> DOC: Correct period of ThreeFry and Philox

- .drone.yml
- appveyor.yml
- ci/azure/azure_template_posix.yml
- ci/azure/install-posix.sh
- doc/source/change-log.rst
- doc/source/extended-generator.rst
- randomgen/distributions.pxd
- randomgen/generator.pyi
- randomgen/generator.pyx
- randomgen/src/distributions/distributions.c
- randomgen/src/distributions/distributions.h
- randomgen/tests/test_extended_generator.py
- requirements-dev.txt
Add Wishart and Pseudo Wishart distribustions
> ENH: Add Wishart and Pseudo-Wishart distributions

- doc/source/change-log.rst
- doc/source/names_wordlist.txt
- doc/source/spelling_wordlist.txt
- randomgen/common.pyx
- randomgen/generator.pyx
- randomgen/rdrand.pyx
- randomgen/tests/test_extended_generator.py
Port output check
Test more edge cases
> MAINT: Port output check from NumPy

- doc/source/conf.py
- doc/source/extended-generator.rst
- randomgen/tests/test_direct.py
- randomgen/tests/test_extended_generator.py
- setup.py
- tools/prng-tester.py
- tools/shared.py
- tools/test-seed-correlation.py
Directly test correctness of long doubles
> TST: Add direct test for long doubles

- benchmark.py
- randomgen/pcg64.pyx
- randomgen/tests/data/stable_hashes.py
Correct variant names and default
> BUG: Correct variant detectionin PCG64

- randomgen/src/xoroshiro128/xoroshiro128.c
- randomgen/tests/test_wrapper_numba.py
- randomgen/xoroshiro128.pyx
Correct function calls
Fix numba warning
closes #321
> BUG: Correct xoroshiro128 jump

- doc/source/multithreading.rst
Correct docs
Fix for new code
closes #356
> DOC: Correct docs

- randomgen/wrapper.pyx
> DOC: Add warning to UBG
