bashtage/randomgen

README.md, benchmark.py, core_prng/common.pxd, core_prng/distributions.pxd, core_prng/dsfmt.pyx, core_prng/generator.pyx, core_prng/mt19937.pyx, core_prng/pcg32.pyx, core_prng/pcg64.pyx, core_prng/philox.pyx, core_prng/src/distributions/distributions.c, core_prng/src/distributions/distributions.h, core_prng/threefry.pyx, core_prng/threefry32.pyx, core_prng/xoroshiro128.pyx, core_prng/xorshift1024.pyx
Remove binomial_t from each prng_state and use a single implementation
at the level of a RandomGenerator
=> REF: Remove binomial_t from prng

randomgen/src/distributions/distributions.c, randomgen/src/distributions/distributions.h
Use MIN and MAX to avoid issues with c++ compilation
xref #20
=> REF: Rename min and max macros

randomgen/bounded_integers.pyx.in
Clarify that the internal generator is closed on [low, high-1] even though
the external interface is open [low, high)
closes #26
=> DOC: Provide a better explanation of bounded int generation

randomgen/src/distributions/distributions.c, randomgen/src/legacy/distributions-boxmuller.c, randomgen/tests/test_legacy.py, randomgen/tests/test_numpy_mt19937.py, randomgen/tests/test_numpy_mt19937_regressions.py
Add protection for 0 input for gamma random variables
Add protection in legacy for gamma random variables
Add protection for 0 input in Weibull
Add test of 0 protection
=> BUG: Protect gamma generation from 0 input

randomgen/src/distributions/distributions.c
Exit early when n=0 in binomial to avoid potential rejection sampling infinite
loop
=> BUG: Exit immediately for n=0 in binomial

.coveragerc, randomgen/tests/test_numpy_mt19937.py
Reenable incorrectly indented test
Exclude pxd files
=> TST: Correct test coverage

setup.py
Currently `setup.py` assumes the default encoding is `utf-8`. In fact, this is system dependent and will cause randomgen to fail to build on a system which has the wrong default encoding (I discovered this when trying to build randomgen in a docker container which for some reason had a default encoding of `ANSI_X3.4-1968`.
This one-line patch explicitly sets the encoding when reading `README.rst` to  `utf-8`.
=> Set the correct input encoding

randomgen/generator.pyx, randomgen/tests/test_generator_mt19937.py
Ensure that choice uses int64 for all paths/platforms
xref numpy/numpy#9867
=> ENH: Ensure choice uses a consistent return type

randomgen/generator.pyx, randomgen/tests/test_against_numpy.py
Use a consistent int64 style for randint accross platforms
=> ENH: Use a consistent dtype for randint

randomgen/bounded_integers.pyx.in, randomgen/generator.pyx, randomgen/tests/test_direct.py, randomgen/tests/test_generator_mt19937.py
Add path the avoids object when possible
=> WIP/ENH: Add fast path for integer dtypes in int64/uint64

doc/source/change-log.rst, randomgen/bounded_integers.pxd.in, randomgen/bounded_integers.pyx.in, randomgen/generator.pyx, randomgen/mtrand.pyx, randomgen/tests/test_generator_mt19937.py
Add closed interval sampling to randint to simplify using int64/uint64
when the range may be full
=> ENH: Add closed interval sampling to randint

randomgen/dsfmt.pyx, randomgen/mt19937.pyx, randomgen/pcg32.pyx, randomgen/pcg64.pyx, randomgen/philox.pyx, randomgen/threefry.pyx, randomgen/threefry32.pyx, randomgen/xoroshiro128.pyx, randomgen/xorshift1024.pyx, randomgen/xoshiro256starstar.pyx, randomgen/xoshiro512starstar.pyx
Use stack rather than heap allocation
=> REF: Stack allocate brng

randomgen/bounded_integers.pyx.in
Use >= or > as appropriate for open or closed intervals
=> BUG: Correct error depending on interval type

doc/source/bit_generators/dsfmt.rst, doc/source/bit_generators/mt19937.rst, doc/source/bit_generators/pcg32.rst, doc/source/bit_generators/pcg64.rst, doc/source/bit_generators/philox.rst, doc/source/bit_generators/threefry.rst, doc/source/bit_generators/threefry32.rst, doc/source/bit_generators/xoroshiro128.rst, doc/source/bit_generators/xorshift1024.rst, doc/source/bit_generators/xoshiro256starstar.rst, doc/source/bit_generators/xoshiro512starstar.rst, doc/source/index.rst, doc/source/multithreading.rst, doc/source/parallel.rst, randomgen/dsfmt.pyx, randomgen/mt19937.pyx, randomgen/pcg32.pyx, randomgen/pcg64.pyx, randomgen/philox.pyx, randomgen/tests/test_smoke.py, randomgen/threefry.pyx, randomgen/threefry32.pyx, randomgen/xoroshiro128.pyx, randomgen/xorshift1024.pyx, randomgen/xoshiro256starstar.pyx, randomgen/xoshiro512starstar.pyx
Deprecate jump and move to new method jumped
jumped returns a new instance
=> MAINT: Rename jump to jumped and deprecate

benchmark.py, doc/source/performance.py, randomgen/src/mt19937/mt19937.c, randomgen/src/mt19937/mt19937.h, randomgen/src/pcg64/pcg64.c, randomgen/src/pcg64/pcg64.h, randomgen/src/philox/philox.h
Use a standard pattern to force inline
=> MAINT: Ensure inline forcing is correct

randomgen/dsfmt.pyx, randomgen/sfmt.pyx, randomgen/src/dsfmt/dSFMT.h, randomgen/tests/test_direct.py
Remove unused buffers from dSFMT
Add to reset in SFMT
Add test for these
=> BUG/MAINT: Correct uinteger buffering in SFMT and dSFMT

randomgen/src/aesctr/aesctr.c, randomgen/src/aesctr/aesctr.h, randomgen/src/chacha/chacha.h, randomgen/src/common/randomgen_immintrin.h, randomgen/src/rdrand/rdrand.h, randomgen/src/speck-128/speck-128-common.h, randomgen/src/speck-128/speck-128-sse.h, randomgen/src/speck-128/speck-128.c, randomgen/src/speck-128/speck-128.h, setup.py
Refactor compiler support for features to follow GCC-like pattern
=> MAINT: Refactor SSE2+ detection

randomgen/mt64.pxd, randomgen/mt64.pyx, randomgen/tests/test_direct.py
Reset value after seed on MT64
Add test for all generators
=> BUG: Ensure 32 bit value is reset after seed

randomgen/src/chacha/chacha.h
Undef before def to avoid some noise
=> MAINT: Undef __mm_roti_epi32

doc/source/change-log.rst, randomgen/src/distributions/distributions.c, randomgen/src/legacy/legacy-distributions.c, randomgen/tests/test_randomstate_regression.py
Fix bug in randint which did not route 2**32 high values to the
32-bit generator. This fix breaks the stream in Generator if
this function call was made.
=> BUG: Fix edge value in randint

randomgen/src/distributions/distributions.c, randomgen/tests/test_final_release_changes.py
Avoid upcasting when negating small unsigned values
=> BUG: Fix bug identified in uint8 and uint16 implementations of Lemire

.travis.yml, randomgen/generator.pyx, randomgen/mtrand.pyx, randomgen/src/distributions/distributions.c, randomgen/tests/test_generator_117.py, randomgen/tests/test_recent_numpy_changes.py
=> BUG: Sync upstream bug fixes

doc/requirements.txt, doc/source/change-log.rst, doc/source/conf.py, doc/source/generator.rst, doc/source/index.rst, doc/source/legacy.rst, randomgen/bounded_integers.pyx.in, randomgen/dsfmt.pyx, randomgen/entropy.pyx, randomgen/generator.pyx, randomgen/legacy/bounded_integers.pyx.in, randomgen/wrapper.pyx
Implement changes coming in 2.0.0
FIx small nits
Update requirements
=> DOC: Fix docs
